name: Build Module

on:
  push:
    branches:
      - main
      - master  # 兼容不同默認分支名
  workflow_dispatch: # 允許手動點擊按鈕運行

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # 確保有權限寫入 Release
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Zip Module
        run: |
          # 排除不必要的文件，打包其餘內容
          zip -r Integrity-Box-v1.zip . -x ".git/*" ".github/*" ".gitignore" "README.md"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Integrity-Box-Zip
          path: Integrity-Box-v1.zip
